apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "renovate-server.fullname" . }}
  labels:
    {{- include "renovate-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "renovate-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "renovate-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
    spec:
      serviceAccountName: {{ include "renovate-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: renovate-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config
            - /etc/renovate-server/config.yaml
          ports:
            - name: http
              containerPort: 8080
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/renovate-server
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "renovate-server.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
